### ISSUE TITLE
Sending data to aprs.fi

### ISSUE THREAD

**Issue by ph0dv** [rubund/gnuais#8]
Hello,

I'm trying to send data to aprs.fi but withouth any succes. When i use >cmake . i see one missing package. Is this package necessary for uploading data to aprs.fi?

root@ph0dv://gnuais# cmake .
-- Looking for include file alsa/asoundlib.h
-- Looking for include file alsa/asoundlib.h - found
-- Looking for include file mysql/mysql.h
-- Looking for include file mysql/mysql.h - found
-- Looking for include file curl/curl.h
-- Looking for include file curl/curl.h - found
-- Looking for include file pulse/pulseaudio.h
-- Looking for include file pulse/pulseaudio.h - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gtk+-3.0'
--   found gtk+-3.0, version 3.14.5
-- checking for module 'gthread-2.0'
--   found gthread-2.0, version 2.42.1
-- checking for module 'osmgpsmap-1.0>=1.0.2'
--   package 'osmgpsmap-1.0>=1.0.2' not found
Missing one more packages for building gui. Skipping
-- Configuring done
-- Generating done
-- Build files have been written to: //gnuais

I'm receiving data (example):
ch A type 3 mmsi 244700617: lat 52.252517 lon 5.322463 course 360 speed 0.0 rateofturn 96 navstat 1 heading 511 (!AIVDM,1,1,,A,33aGEjEP00PHGD<MqRmf4?wV2DFb,0*00)

And it's written to the database:
mysql> SELECT * from ais_vesseldata;
+----+------------+-----------+-------------+---------------------+---------+------+------+------+------+
| id | time       | mmsi      | name        | destination         | draught | A    | B    | C    | D    |
+----+------------+-----------+-------------+---------------------+---------+------+------+------+------+
|  2 | 1495879205 | 244620315 | AGAPE       | CLASS B             |    NULL |    9 |    2 |    1 |    3 |
|  4 | 1495879289 | 244860885 | MARIA       | CLASS B             |    NULL | NULL | NULL | NULL | NULL |
|  5 | 1495879223 | 244690810 | MARGRIET    | MUIDERBERG/LELYSTAD |     0.2 |   18 |    0 |    3 |    3 |
|  6 | 1495879651 | 244090345 | SCHONE MARE | CLASS B             |    NULL |    6 |    6 |    2 |    2 |
+----+------------+-----------+-------------+---------------------+---------+------+------+------+------+
4 rows in set (0.00 sec)

My settings in the config:
# Uplink <name> <protocol> <url>
Uplink aprs.fi json http://aprs.fi/jsonais/post/my_ais_password

(my ais password changed)

Is there a log were i can see if it's uploading data?
Or has this to do with package 'osmgpsmap-1.0>=1.0.2' not found?

Or any other suggestions?

I'm running debian8 jesse.

Thank you,

DIck Vos
PH0DV

**Comment by ph0dv** [comment]
Installing osm-gsm-map fixed the error.

See this topic how to do this: https://github.com/nzjrs/osm-gps-map/issues/58

root@ph0dv://gnuais# cmake .
-- Looking for include file alsa/asoundlib.h
-- Looking for include file alsa/asoundlib.h - found
-- Looking for include file mysql/mysql.h
-- Looking for include file mysql/mysql.h - found
-- Looking for include file curl/curl.h
-- Looking for include file curl/curl.h - found
-- Looking for include file pulse/pulseaudio.h
-- Looking for include file pulse/pulseaudio.h - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gtk+-3.0'
--   found gtk+-3.0, version 3.14.5
-- checking for module 'gthread-2.0'
--   found gthread-2.0, version 2.42.1
-- checking for module 'osmgpsmap-1.0>=1.0.2'
--   found osmgpsmap-1.0, version 1.1.0
-- Configuring done
-- Generating done
-- Build files have been written to: //gnuais

Now see if it works.

**Comment by ph0dv** [comment]
Stil no ships on aprs.fi.

Can i see if it's sending data in log?

**Comment by ph0dv** [comment]
You need to set the correct time. On Jesse 

apt-get install ntp

did do the job.

**Comment by SewafieX** [comment]
I set the GNUAIS to read from pulseaudio, but it's getting 0% on channel A and B. What and how do I connect the info that the rtl-sdr is receiving to pulseaudio? I can't find any documentation on GNU AIS, so your help and clarification would very appreciated. Thanks in advance.
